version: '3.2'

services:
  db:
    restart: always
    image: postgres:11
    container_name: mlflow_db
    ports:
      - "5432:5432"
    networks:
      - A
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DATABASE=${PG_DATABASE}
    volumes:
      - ./db_data:/var/lib/postgresql/data/
  mlflow:
      container_name: tracker_mlflow
      image: tracker_ml
      build:
          context: ./mlflow
          dockerfile: Dockerfile
      ports:
        - "5000:5000"
      environment: 
        - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
        - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_ACCESS_KEY}
      networks:
          - A
      entrypoint: ./wait-for-it.sh db:5432 -t 60 -- mlflow server --backend-store-uri postgresql://${PG_USER}:${PG_PASSWORD}@db:${PG_PORT}/${PG_DATABASE} --default-artifact-root s3://${MLFLOW_BUCKET_NAME}/ -h 0.0.0.0


networks:
    A:
      driver: bridge